package org.firstinspires.ftc.teamcode.constants;

public final class Vuforia {

    public static final String VUFORIA_KEY = "AX9Tt1f/////AAAAmZgP0a7xc00OtCKro8AxNIB0Ga4OEzIbXne8gRzbrIWLbdDHycjj1xMWsNBKrsRDAEiWKN3LTwH77nbmYSVM4LeDtJodEejVAlG6J+U0m1UhTz8+tvYYfOSptuQWhhIo3bJQS/ZZo0IO/emnTgjgcBU9S9dMdIxFTHA71SPKsoMaNyE+yFGgVur3UbU9uY0oPBzRnPEFW4GB1hVaV8LQHLRYCd7/6H1fqDggix7GCKpNzw5y/1mCTGJxTRTI+j//ZhvtW6PUCHYxPyRLUzjy/wTettLuB6oTslQDW3UTuxq6dCjOHJskVNVWVkFlTiWk1oxkjqhBd6Px60nwHHNL038o2WZUitk2whtkFkhB6DYX";

}
